### ISSUE TITLE
auth_dirs.inc: No such file or directory

### ISSUE THREAD

**Issue by dirkbeer** [ATOR-Development/ator-protocol#5]
I get this error when running `make` on Fedora 39.

**Comment by dirkbeer** [comment]
Get the same message when doing `docker build -t ator-protocol`:
`806.9   CC       src/app/config/config.o
807.0 src/app/config/config.c:786:10: fatal error: auth_dirs.inc: No such file or directory
807.0   786 | #include "auth_dirs.inc"
807.0       |          ^~~~~~~~~~~~~~~
807.0 compilation terminated.`

**Comment by floodcode** [comment]
Fixed in #7, thanks for reporting!
